############################################################
# Phillipian Upload Automation Development Environment     #
#    Languages                                             #
#        python 3.7                                        #
#    Tools                                                 #
#                                                          #
############################################################

FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt